/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.chribonsi.vector_rally;

public class App {
    public static void main(String[] args) {
        //real flow
        System.out.println("starting game...");
        SimpleGameManager gameManager = new SimpleGameManager();
        gameManager.startRace();
    }
}
