/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.chribonsi.vector_rally;

import java.util.Map;

public class App {
    public static void main(String[] args) {
        /*
         * App istanzia nuovo GameManager --> nel costruttore viene creato un nuovo IOManager -->
         * -> ciclo per inserimento path --> creata Schematic dal path che parsa tutto -->
         * -> istanziato nuovo Racetrack --> startRace()
         */
        System.out.println("starting game...");
        SimpleGameManager gameManager = new SimpleGameManager();
        if (gameManager.startRace()) {
            printLeaderboard(gameManager.getLeaderboard());
        } else throw new RuntimeException("Game Over without any winner!");
    }

    private static void printLeaderboard(Map<Player, Integer> leaderboard) {
        System.out.println("\nLeaderboard:");
        for (Map.Entry<Player, Integer> entry : leaderboard.entrySet()) {
            System.out.println("The Player '" + entry.getKey().getName() + "' finished in position #" + entry.getValue());
        }
        System.out.println("Congratulations to the winner!\nGame Over");
    }
}
